FROM python:3.9

WORKDIR /BlogSystem

COPY requirements.txt /BlogSystem/
RUN pip install -r requirements.txt

COPY . /BlogSystem/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]